# Generated by Django 2.2.6 on 2019-10-17 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20191015_0653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
