# Generated by Django 2.2.6 on 2019-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
